import { Page, Mention } from './types';

export const SEED_PAGES: Page[] = [
  // Conversation Turn Message Pages (Each turn contains user_prompt + assistant response content)
  {
    id: 'note-1',
    type: 'message',
    role: 'assistant',
    title: 'Next.js 15 & Tailwind v4 Migration',
    user_prompt: 'We need to plan our migration to Next.js 15 App Router and TailwindCSS v4 for our analytics dashboard. What are the key architectural decisions and action items?',
    content: 'I reviewed the upgrade path for [@Next.js] and [@TailwindCSS]. Here are the recommended architectural decisions and immediate tasks:\n\n[@decision: Adopt React 19 Async Server Components with React Compiler for automatic memoization]\n[@decision: Migrate custom CSS utility classes to CSS variables with Tailwind v4 theme directives]\n\nAction items for the team:\n[@todo: Upgrade Next.js packages and test server action mutations]\n[@todo: Replace legacy tailwind.config.js with CSS theme configuration file]',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'note-2',
    type: 'message',
    role: 'assistant',
    title: 'Realtime Telemetry & Data Layer',
    user_prompt: 'How should we handle live real-time metrics streaming and offline telemetry storage?',
    content: 'For real-time telemetry streaming with low overhead:\n\n[@decision: Use WebSocket broadcast channels paired with Supabase Realtime for live dashboard metrics]\n[@decision: Store offline telemetry drafts in IndexedDB before syncing to server]\n\nTasks to complete:\n[@todo: Implement WebSocket reconnect handler with exponential backoff]\n[@todo: Benchmark IndexedDB read throughput for batch metric payload writes]\n\nReferenced stack components: [@Supabase], [@Next.js].',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },

  // User Notes
  {
    id: 'user-note-1',
    type: 'note',
    title: 'Architecture Overview & Stack Notes',
    content: 'Personal workspace note covering key technical considerations for [@Next.js] migration, [@Supabase] real-time metrics, and [@TailwindCSS] theme directives.',
    created_at: new Date(Date.now() - 86400000 * 0.5).toISOString(),
  },

  // Tracked Entity Pages (User Created Manually)
  {
    id: 'ent-1',
    type: 'entity',
    title: 'Next.js',
    content: 'React framework for server-rendered web applications with App Router.',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'ent-2',
    type: 'entity',
    title: 'TailwindCSS',
    content: 'Utility-first CSS framework with native CSS variable theme engine.',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'ent-3',
    type: 'entity',
    title: 'Supabase',
    content: 'Open-source Backend-as-a-Service providing Realtime WebSockets and PostgreSQL database.',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },

  // Todo Pages (LLM or User Tagged)
  {
    id: 'todo-1',
    type: 'todo',
    title: 'Upgrade Next.js packages and test server action mutations',
    content: 'Upgrade Next.js packages to v15.2 and test server action mutations for analytical forms.',
    done: false,
    starred: true,
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'todo-2',
    type: 'todo',
    title: 'Replace legacy tailwind.config.js with CSS theme configuration file',
    content: 'Replace legacy tailwind.config.js with CSS theme configuration using native @theme directives.',
    done: false,
    starred: false,
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'todo-3',
    type: 'todo',
    title: 'Implement WebSocket reconnect handler with exponential backoff',
    content: 'Implement WebSocket reconnect handler with exponential backoff for Supabase telemetry channels.',
    done: true,
    starred: true,
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
  {
    id: 'todo-4',
    type: 'todo',
    title: 'Benchmark IndexedDB read throughput for batch metric payload writes',
    content: 'Benchmark IndexedDB read throughput for batch metric payload writes during offline network dropouts.',
    done: false,
    starred: false,
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },

  // Decision Pages (LLM or User Tagged)
  {
    id: 'dec-1',
    type: 'decision',
    title: 'Adopt React 19 Async Server Components with React Compiler for automatic memoization',
    content: 'Agreed architectural decision to adopt React 19 Async Server Components and enable React Compiler for optimized render cycles.',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'dec-2',
    type: 'decision',
    title: 'Migrate custom CSS utility classes to CSS variables with Tailwind v4 theme directives',
    content: 'Standardize design system color tokens using native CSS custom properties in Tailwind CSS v4 directives.',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'dec-3',
    type: 'decision',
    title: 'Use WebSocket broadcast channels paired with Supabase Realtime for live dashboard metrics',
    content: 'Architecture decision to stream real-time dashboard updates over Supabase Realtime WebSockets.',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
  {
    id: 'dec-4',
    type: 'decision',
    title: 'Store offline telemetry drafts in IndexedDB before syncing to server',
    content: 'Enforce client-side offline durability by writing transient telemetry payloads to browser IndexedDB.',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
];

export const SEED_MENTIONS: Mention[] = [
  {
    id: 'men-1',
    target_page_id: 'ent-1',
    source_page_id: 'note-1',
    snippet: 'I reviewed the upgrade path for [@Next.js]',
    source: 'manual',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'men-2',
    target_page_id: 'ent-2',
    source_page_id: 'note-1',
    snippet: 'upgrade path for Next.js and [@TailwindCSS]',
    source: 'manual',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'men-3',
    target_page_id: 'dec-1',
    source_page_id: 'note-1',
    snippet: '[@decision: Adopt React 19 Async Server Components with React Compiler for automatic memoization]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'men-4',
    target_page_id: 'dec-2',
    source_page_id: 'note-1',
    snippet: '[@decision: Migrate custom CSS utility classes to CSS variables with Tailwind v4 theme directives]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'men-5',
    target_page_id: 'todo-1',
    source_page_id: 'note-1',
    snippet: '[@todo: Upgrade Next.js packages and test server action mutations]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'men-6',
    target_page_id: 'todo-2',
    source_page_id: 'note-1',
    snippet: '[@todo: Replace legacy tailwind.config.js with CSS theme configuration file]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 2.8).toISOString(),
  },
  {
    id: 'men-7',
    target_page_id: 'dec-3',
    source_page_id: 'note-2',
    snippet: '[@decision: Use WebSocket broadcast channels paired with Supabase Realtime for live dashboard metrics]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
  {
    id: 'men-8',
    target_page_id: 'dec-4',
    source_page_id: 'note-2',
    snippet: '[@decision: Store offline telemetry drafts in IndexedDB before syncing to server]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
  {
    id: 'men-9',
    target_page_id: 'todo-3',
    source_page_id: 'note-2',
    snippet: '[@todo: Implement WebSocket reconnect handler with exponential backoff]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
  {
    id: 'men-10',
    target_page_id: 'todo-4',
    source_page_id: 'note-2',
    snippet: '[@todo: Benchmark IndexedDB read throughput for batch metric payload writes]',
    source: 'auto',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
  {
    id: 'men-11',
    target_page_id: 'ent-3',
    source_page_id: 'note-2',
    snippet: 'Referenced stack components: [@Supabase], [@Next.js]',
    source: 'manual',
    created_at: new Date(Date.now() - 86400000 * 1.2).toISOString(),
  },
];
